apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cheinstallations.toolchain.openshift.dev
spec:
  group: toolchain.openshift.dev
  names:
    kind: CheInstallation
    listKind: CheInstallationList
    plural: cheinstallations
    singular: cheinstallation
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CheInstallation is the Schema for the cheinstallations API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CheInstallationSpec defines the desired state of CheInstallation
          properties:
            cheOperatorSpec:
              description: The configuration required for che operator
              properties:
                namespace:
                  description: The namespace where the Che operator will be installed
                  type: string
              required:
              - namespace
              type: object
          required:
          - cheOperatorSpec
          type: object
        status:
          description: CheInstallationStatus defines the observed state of CheInstallation
          properties:
            conditions:
              description: 'Conditions is an array of current CheInstallation conditions
                Supported condition types: CheInstalled, FailedToInstallChe'
              items:
                $ref: '#/definitions/github.com~1codeready-toolchain~1api~1pkg~1apis~1toolchain~1v1alpha1~0Condition'
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
