kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: toolchain-operator
subjects:
  - kind: ServiceAccount
    name: toolchain-operator
    namespace: REPLACE_NAMESPACE
roleRef:
  kind: ClusterRole
  name: toolchain-operator
  apiGroup: rbac.authorization.k8s.io
